/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.hclsope.ui.internal.HclsopeActivator;

public class HclScopeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HclsopeActivator.getInstance().getInjector("org.xtext.example.hclscope.HclScope");
	}

}
