/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.hclsope.ui.internal.HclsopeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HclScopeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(HclsopeActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		HclsopeActivator activator = HclsopeActivator.getInstance();
		return activator != null ? activator.getInjector(HclsopeActivator.ORG_XTEXT_EXAMPLE_HCLSCOPE_HCLSCOPE) : null;
	}

}
